[package]
name = "Parser"
version = "0.1.0"
authors = ["se"]

[dependencies]
conv = "0.3.1"
image = "0.20.0"
itertools = "0.7.0"
num = "0.2.0"
quickcheck = "0.6"
rand = "0.4.0"
rusttype = "0.7"
rayon = "1.0"
imageproc = "0.16.0"
